// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhPtaO9Xzq_8UKyYCQQsFWjmwhHsZwMEI',
    appId: '1:703120703575:web:6ca3a3732881b738a3a312',
    messagingSenderId: '703120703575',
    projectId: 'firebase-to-do-app',
    authDomain: 'fir-to-do-app-e6dc9.firebaseapp.com',
    storageBucket: 'firebase-to-do-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlMFwEDuC_dJjNvgO4Yy4ieZxDlMaPntk',
    appId: '1:703120703575:android:e6ad941686e6063ba3a312',
    messagingSenderId: '703120703575',
    projectId: 'firebase-to-do-app',
    storageBucket: 'firebase-to-do-app.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhPtaO9Xzq_8UKyYCQQsFWjmwhHsZwMEI',
    appId: '1:703120703575:web:cfb51424b0ed29bda3a312',
    messagingSenderId: '703120703575',
    projectId: 'firebase-to-do-app',
    authDomain: 'fir-to-do-app-e6dc9.firebaseapp.com',
    storageBucket: 'firebase-to-do-app.appspot.com',
  );
}
